/*
 * This  source file was generated by the Gradle 'init' task.
 */
package lib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

   public static int BinarySearch(int[] arrayTow,int n){
    int num =-1 ;
    for(int i=0;i<arrayTow.length/4;i++){
      if(n==arrayTow[i]){
       num=i;
      }
    }
     for(int i=0;i<arrayTow.length/2;i++){
      if(n==arrayTow[i]){
       num=i ;

      }
    }
     for(int i=0;i<arrayTow.length;i++){
      if(n==arrayTow[i]){
        num=i;

      }else if(num==-1){
        num=-1 ;
      }
    }
    
    return num ;

  }
}
